### PR TITLE
add new dataset

### PR DESCRIPTION
**Pull request by stemangiola**

### CODE REVIEW

**Comment by mblue9** [comment]
I tried testing this PR before your commits this afternoon but I get a different error to here, one with the ## Scaling and Integrating code block below that was making my computer unhappy. I tried updating to current tidyseurat but get same error. So I'll wait to see if the other error here appears again and can try updating tidyseurat here then.

Problem with `mutate()` input `data`.
ℹ iteration limit reached
ℹ Input `data` is `map(data, ~SCTransform(.x, verbose = FALSE))`.iteration limit reachedProblem with `mutate()` input `data`.
ℹ iteration limit reached
ℹ Input `data` is `map(data, ~SCTransform(.x, verbose = FALSE))`.iteration limit reachedProblem with `mutate()` input `data`.
ℹ iteration limit reached
ℹ Input `data` is `map(data, ~SCTransform(.x, verbose = FALSE))`.iteration limit reachedProblem with `mutate()` input `data`.
ℹ iteration limit reached
ℹ Input `data` is `map(data, ~SCTransform(.x, verbose = FALSE))`.iteration limit reachedProblem with `mutate()` input `data`.
ℹ iteration limit reached
ℹ Input `data` is `map(data, ~SCTransform(.x, verbose = FALSE))`.iteration limit reachedProblem with `mutate()` input `data`.
ℹ iteration limit reached
ℹ Input `data` is `map(data, ~SCTransform(.x, verbose = FALSE))`.iteration limit reachedProblem with `mutate()` input `data`.
```

**Comment by mblue9** [comment]
The current error here
```
Quitting from lines 946-951 (tidytranscriptomics.Rmd) 
Error: processing vignette 'tidytranscriptomics.Rmd' failed with diagnostics:
NA/NaN/Inf in foreign function call (arg 2)
--- failed re-building ‘tidytranscriptomics.Rmd’
```

 I also get locally with tidyseurat 0.1.17


```{r umap seurat}
pbmc_UMAP <-
  pbmc_integrated %>%
  FindVariableFeatures(verbose = FALSE) %>%
  RunPCA(verbose = FALSE) %>%
  RunUMAP(reduction = "pca", dims = 1:15, n.components = 3L)
```
`Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric, : NA/NaN/Inf in foreign function call (arg 2)`

**Comment by stemangiola** [comment]
So strange I don't get it locally. If only I could reproduce to fix. Tomorrow I will google a possible solution.

**Comment by mblue9** [comment]
ok cool, this is my sessioninfo in case it helps

```> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tidyseurat_0.1.17                   celldex_1.0.0                       EnsDb.Hsapiens.v86_2.99.0          
 [4] ensembldb_2.14.0                    AnnotationFilter_1.14.0             GenomicFeatures_1.42.1             
 [7] AnnotationDbi_1.52.0                scuttle_1.0.2                       SingleCellExperiment_1.12.0        
[10] SingleR_1.4.0                       Seurat_3.2.2                        purrr_0.3.4                        
[13] ABACBS2020tidytranscriptomics_0.1.0 survival_3.2-7                      tidybulk_1.2.0                     
[16] tidyHeatmap_1.1.5                   GGally_2.0.0                        ggrepel_0.8.2                      
[19] plotly_4.9.2.1                      ggplot2_3.3.2                       stringr_1.4.0                      
[22] readr_1.4.0                         tidyr_1.1.2                         dplyr_1.0.2                        
[25] tibble_3.0.4                        airway_1.10.0                       SummarizedExperiment_1.20.0        
[28] Biobase_2.50.0                      GenomicRanges_1.42.0                GenomeInfoDb_1.26.1                
[31] IRanges_2.24.0                      S4Vectors_0.28.0                    BiocGenerics_0.36.0                
[34] MatrixGenerics_1.2.0                matrixStats_0.57.0                 

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.1                rtracklayer_1.50.0            bit64_4.0.5                   knitr_1.30                   
  [5] irlba_2.3.3                   DelayedArray_0.16.0           data.table_1.13.2             rpart_4.1-15                 
  [9] RCurl_1.98-1.2                generics_0.1.0                preprocessCore_1.52.0         callr_3.5.1                  
 [13] cowplot_1.1.0                 usethis_1.6.3                 RSQLite_2.2.1                 RANN_2.6.1                   
 [17] future_1.20.1                 bit_4.0.4                     spatstat.data_1.5-2           xml2_1.3.2                   
 [21] httpuv_1.5.4                  assertthat_0.2.1              viridis_0.5.1                 xfun_0.19                    
 [25] hms_0.5.3                     promises_1.1.1                fansi_0.4.1                   progress_1.2.2               
 [29] dbplyr_2.0.0                  igraph_1.2.6                  DBI_1.1.0                     geneplotter_1.68.0           
 [33] htmlwidgets_1.5.2             reshape_0.8.8                 ellipsis_0.3.1                crosstalk_1.1.0.1            
 [37] backports_1.2.0               annotate_1.68.0               biomaRt_2.46.0                deldir_0.2-3                 
 [41] sparseMatrixStats_1.2.0       vctrs_0.3.5                   remotes_2.2.0                 Cairo_1.5-12.2               
 [45] ROCR_1.0-11                   abind_1.4-5                   withr_2.3.0                   sctransform_0.3.1            
 [49] GenomicAlignments_1.26.0      prettyunits_1.1.1             dittoSeq_1.2.1                goftest_1.2-2                
 [53] cluster_2.1.0                 ExperimentHub_1.16.0          lazyeval_0.2.2                crayon_1.3.4                 
 [57] genefilter_1.72.0             edgeR_3.32.0                  pkgconfig_2.0.3               labeling_0.4.2               
 [61] ProtGenerics_1.22.0           nlme_3.1-150                  vipor_0.4.5                   pkgload_1.1.0                
 [65] devtools_2.3.2                rlang_0.4.8                   globals_0.14.0                lifecycle_0.2.0              
 [69] miniUI_0.1.1.1                BiocFileCache_1.14.0          rsvd_1.0.3                    AnnotationHub_2.22.0         
 [73] rprojroot_2.0.2               polyclip_1.10-0               lmtest_0.9-38                 Matrix_1.2-18                
 [77] boot_1.3-25                   zoo_1.8-8                     beeswarm_0.2.3                ggridges_0.5.2               
 [81] GlobalOptions_0.1.2           processx_3.4.4                pheatmap_1.0.12               png_0.1-7                    
 [85] viridisLite_0.3.0             rjson_0.2.20                  bitops_1.0-6                  KernSmooth_2.23-18           
 [89] Biostrings_2.58.0             blob_1.2.1                    DelayedMatrixStats_1.12.0     shape_1.4.5                  
 [93] parallelly_1.21.0             beachmat_2.6.1                scales_1.1.1                  memoise_1.1.0                
 [97] magrittr_2.0.1                plyr_1.8.6                    ica_1.0-2                     zlibbioc_1.36.0              
[101] compiler_4.0.2                RColorBrewer_1.1-2            tidygate_0.2.8                clue_0.3-57                  
[105] DESeq2_1.30.0                 fitdistrplus_1.1-1            Rsamtools_2.6.0               cli_2.2.0                    
[109] XVector_0.30.0                listenv_0.8.0                 patchwork_1.1.0               pbapply_1.4-3                
[113] ps_1.4.0                      MASS_7.3-53                   mgcv_1.8-33                   tidyselect_1.1.0             
[117] stringi_1.5.3                 forcats_0.5.0                 yaml_2.2.1                    BiocSingular_1.6.0           
[121] askpass_1.1                   locfit_1.5-9.4                grid_4.0.2                    tools_4.0.2                  
[125] future.apply_1.6.0            circlize_0.4.11               rstudioapi_0.13               gridExtra_2.3                
[129] farver_2.0.3                  Rtsne_0.15                    BiocManager_1.30.10           digest_0.6.27                
[133] shiny_1.5.0                   Rcpp_1.0.5                    broom_0.7.2                   BiocVersion_3.12.0           
[137] later_1.1.0.1                 RcppAnnoy_0.0.17              org.Hs.eg.db_3.12.0           httr_1.4.2                   
[141] ComplexHeatmap_2.6.2          colorspace_2.0-0              XML_3.99-0.5                  fs_1.5.0                     
[145] tensor_1.5                    reticulate_1.18               splines_4.0.2                 uwot_0.1.9                   
[149] spatstat.utils_1.17-0         sessioninfo_1.1.1             xtable_1.8-4                  jsonlite_1.7.1               
[153] spatstat_1.64-1               testthat_3.0.0                R6_2.5.0                      pillar_1.4.7                 
[157] htmltools_0.5.0               mime_0.9                      glue_1.4.2                    fastmap_1.0.1                
[161] BiocParallel_1.24.1           BiocNeighbors_1.8.1           interactiveDisplayBase_1.28.0 codetools_0.2-18             
[165] utf8_1.1.4                    pkgbuild_1.1.0                lattice_0.20-41               curl_4.3                     
[169] ggbeeswarm_0.6.0              leiden_0.3.5                  openssl_1.4.3                 limma_3.46.0                 
[173] desc_1.2.0                    munsell_0.5.0                 GetoptLong_1.0.4              GenomeInfoDbData_1.2.4       
[177] reshape2_1.4.4                gtable_0.3.0  
```

**Comment by mblue9** [comment]
Woo hoo this passed the checks and is on the website building stage now.

**Pull request merged**
